import SwiftUI
import AppKit

// App Intents discovery browser — the "Discover" tab of the Capabilities window. Reads the
// `Metadata.appintents/extract.actionsdata` that apps ship (JSON generated by the App Intents
// compiler) to show what actions each installed app exposes to Siri / Spotlight / Shortcuts.
// There's no public API to invoke an arbitrary app's intent directly — Shortcuts is the
// bridge — so this is a discovery surface: see what's possible, then "Teach as capability"
// hands it to the agent to author + save into the Library. The scanner will later also feed
// generated per-app MCP tool schemas.

struct AppIntentParam: Identifiable {
    var id: String { name }
    let name: String
    let title: String
    let optional: Bool
}

struct AppIntentAction: Identifiable {
    let id: String
    let title: String
    let detail: String?
    let parameters: [AppIntentParam]
    let opensApp: Bool
    let discoverable: Bool
}

struct AppIntentApp: Identifiable {
    let id: String
    let name: String
    let bundleURL: URL
    let actions: [AppIntentAction]
    var icon: NSImage { NSWorkspace.shared.icon(forFile: bundleURL.path) }
}

@MainActor
final class AppCapabilitiesStore: ObservableObject {
    static let shared = AppCapabilitiesStore()
    @Published var apps: [AppIntentApp] = []
    @Published var scanning = false
    private var lastScan: Date?
    private var watchers: [DispatchSourceFileSystemObject] = []
    private var rescanWork: DispatchWorkItem?
    private init() {}

    // An immutable array of `String` is already Sendable; it was main-actor isolated only by
    // inheriting the class's isolation, which `scanDisk()` — deliberately nonisolated — cannot read.
    nonisolated static let roots = ["/Applications", "/Applications/Utilities",
                                    "/System/Applications", "/System/Applications/Utilities",
                                    "\(NSHomeDirectory())/Applications"]

    func scanIfNeeded() { if apps.isEmpty && !scanning { scan() } }

    /// Re-scan if the list is older than `maxAge` — cheap way to pick up apps installed/updated
    /// while the Discover tab was closed (the live watcher covers changes while it's open).
    func refreshIfStale(_ maxAge: TimeInterval = 60) {
        if let last = lastScan, Date().timeIntervalSince(last) < maxAge { return }
        scan()
    }

    func scan() {
        guard !scanning else { return }
        scanning = true
        Task.detached(priority: .utility) {
            let found = Self.scanDisk()
            await MainActor.run { self.apps = found; self.scanning = false; self.lastScan = Date() }
        }
    }

    /// Watch the application directories so a newly installed or updated app (Metadata.appintents
    /// changes on update) triggers a debounced rescan while the tab is open. Idempotent.
    func startWatching() {
        guard watchers.isEmpty else { return }
        for root in Self.roots {
            let fd = open(root, O_EVTONLY)
            guard fd >= 0 else { continue }
            let src = DispatchSource.makeFileSystemObjectSource(
                fileDescriptor: fd, eventMask: [.write, .rename, .delete], queue: .main)
            src.setEventHandler { [weak self] in self?.scheduleRescan() }
            src.setCancelHandler { close(fd) }
            src.resume()
            watchers.append(src)
        }
    }

    func stopWatching() {
        rescanWork?.cancel(); rescanWork = nil
        watchers.forEach { $0.cancel() }
        watchers.removeAll()
    }

    // Coalesce a burst of filesystem events (an install writes many files) into one rescan.
    private func scheduleRescan() {
        rescanWork?.cancel()
        let work = DispatchWorkItem { [weak self] in self?.scan() }
        rescanWork = work
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5, execute: work)
    }

    var totalActions: Int { apps.reduce(0) { $0 + $1.actions.count } }

    // MARK: parsing

    private nonisolated static func scanDisk() -> [AppIntentApp] {
        var seen = Set<String>()
        /// Deduped by BUNDLE IDENTIFIER, not file name. Keeping copies of one app apart by name put
        /// "Mechanician-rollback", "Mechanician-rollback-0.11.0" and
        /// "Mechanician-0.10.8-pre-gate-backup" in a user-facing list beside Mail and Keynote —
        /// every one of them the same app with the same actions. Any duplicate bundle id is a
        /// backup, a rollback, or a second install, and only the first copy found is real to the
        /// user (roots are ordered /Applications first).
        var seenBundleIDs = Set<String>()
        var out: [AppIntentApp] = []
        let fm = FileManager.default
        for root in roots {
            guard let names = try? fm.contentsOfDirectory(atPath: root) else { continue }
            for n in names.sorted() where n.hasSuffix(".app") {
                guard !seen.contains(n) else { continue }
                let appURL = URL(fileURLWithPath: root).appendingPathComponent(n)
                let dataURL = appURL.appendingPathComponent(
                    "Contents/Resources/Metadata.appintents/extract.actionsdata")
                guard let data = try? Data(contentsOf: dataURL),
                      let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
                      let actionsDict = json["actions"] as? [String: Any] else { continue }
                let actions = parseActions(actionsDict)
                guard !actions.isEmpty else { continue }
                if let bundleID = Bundle(url: appURL)?.bundleIdentifier {
                    guard seenBundleIDs.insert(bundleID).inserted else { continue }
                }
                seen.insert(n)
                out.append(AppIntentApp(id: appURL.path,
                                        name: (n as NSString).deletingPathExtension,
                                        bundleURL: appURL, actions: actions))
            }
        }
        return out.sorted { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
    }

    /// The App Intents JSON wraps localizable strings as `{ "key": "…", "alternatives": [] }`.
    private nonisolated static func key(_ v: Any?) -> String? { (v as? [String: Any])?["key"] as? String }

    private nonisolated static func parseActions(_ dict: [String: Any]) -> [AppIntentAction] {
        dict.compactMap { (id, raw) -> AppIntentAction? in
            guard let a = raw as? [String: Any] else { return nil }
            let title = key(a["title"]) ?? id
            let detail = key((a["descriptionMetadata"] as? [String: Any])?["descriptionText"])
            let params = (a["parameters"] as? [[String: Any]])?.map { p in
                AppIntentParam(name: p["name"] as? String ?? "?",
                               title: key(p["title"]) ?? (p["name"] as? String ?? "?"),
                               optional: p["isOptional"] as? Bool ?? false)
            } ?? []
            return AppIntentAction(id: id, title: title, detail: detail, parameters: params,
                                   opensApp: a["openAppWhenRun"] as? Bool ?? false,
                                   discoverable: a["isDiscoverable"] as? Bool ?? true)
        }
        .sorted { $0.title.localizedCaseInsensitiveCompare($1.title) == .orderedAscending }
    }
}

/// The Discover tab: apps on the left, the selected app's actions on the right.
struct AppCapabilitiesView: View {
    @ObservedObject private var store = AppCapabilitiesStore.shared
    @State private var selected: String?
    @State private var search = ""

    private var filtered: [AppIntentApp] {
        let q = search.trimmingCharacters(in: .whitespaces)
        guard !q.isEmpty else { return store.apps }
        return store.apps.filter {
            $0.name.localizedCaseInsensitiveContains(q)
                || $0.actions.contains { $0.title.localizedCaseInsensitiveContains(q) }
        }
    }

    private var current: AppIntentApp? {
        filtered.first { $0.id == selected } ?? filtered.first
    }

    var body: some View {
        HSplitView {
            appList.frame(minWidth: 240, idealWidth: 280)
            detail.frame(minWidth: 380)
        }
        .onAppear { store.scanIfNeeded(); store.refreshIfStale(); store.startWatching() }
        .onDisappear { store.stopWatching() }
    }

    private var appList: some View {
        VStack(spacing: 0) {
            HStack(spacing: 6) {
                Image(systemName: "magnifyingglass").foregroundStyle(.secondary)
                TextField("Filter apps & actions", text: $search).textFieldStyle(.plain)
                if store.scanning { ProgressView().controlSize(.small) }
                Button { store.scan() } label: { Image(systemName: "arrow.clockwise") }
                    .buttonStyle(.borderless).help("Rescan").disabled(store.scanning)
                    .accessibilityLabel("Rescan apps")
            }
            .padding(8)
            Divider()
            if store.apps.isEmpty && store.scanning {
                Spacer(); ProgressView("Scanning installed apps…").controlSize(.small); Spacer()
            } else {
                List(filtered, selection: $selected) { app in
                    HStack(spacing: 8) {
                        Image(nsImage: app.icon).resizable().frame(width: 20, height: 20)
                        Text(app.name).lineLimit(1)
                        Spacer()
                        Text("\(app.actions.count)").font(.caption).foregroundStyle(.secondary)
                            .padding(.horizontal, 5).padding(.vertical, 1)
                            .background(Capsule().fill(Color.secondary.opacity(0.15)))
                    }
                    .tag(app.id)
                }
                .listStyle(.inset)
            }
            Divider()
            Text("\(store.apps.count) apps · \(store.totalActions) actions")
                .font(.caption2).foregroundStyle(.secondary).padding(6)
        }
    }

    @ViewBuilder
    private var detail: some View {
        if let app = current {
            ScrollView {
                VStack(alignment: .leading, spacing: 12) {
                    HStack(spacing: 10) {
                        Image(nsImage: app.icon).resizable().frame(width: 40, height: 40)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(app.name).font(.title3.weight(.semibold))
                            Text("\(app.actions.count) actions exposed to Shortcuts / Siri / Spotlight")
                                .font(.caption).foregroundStyle(.secondary)
                        }
                        Spacer()
                        Button("Reveal") { NSWorkspace.shared.activateFileViewerSelecting([app.bundleURL]) }
                            .buttonStyle(PillButtonStyle(kind: .plain))
                    }
                    Divider()
                    ForEach(app.actions) { actionRow(app, $0) }
                }
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
            }
        } else {
            Text("Select an app to see the actions it exposes.")
                .foregroundStyle(.secondary)
                .frame(maxWidth: .infinity, maxHeight: .infinity)
        }
    }

    private func actionRow(_ app: AppIntentApp, _ a: AppIntentAction) -> some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(spacing: 6) {
                Image(systemName: "bolt.fill").font(.caption).foregroundStyle(Color.nInfoText)
                Text(a.title).font(.headline)
                if a.opensApp {
                    tag("opens app", .nWarningText)
                }
                if !a.discoverable { tag("hidden", .secondary) }
                Spacer()
                // Hand this discovered action to the agent to author, test, and save as a
                // reusable capability (AppleScript/JXA — the de-risk ruled out silent Shortcut JIT).
                Button { teach(app, a) } label: { Label("Teach as capability", systemImage: "wand.and.stars") }
                    .controlSize(.small).buttonStyle(.borderless)
                    .help("Ask the agent to build a capability that performs this action")
            }
            if let d = a.detail { Text(d).font(.callout).foregroundStyle(.secondary) }
            if !a.parameters.isEmpty {
                FlowText(a.parameters.map { $0.title + ($0.optional ? "?" : "") })
            }
        }
        .padding(10)
        .frame(maxWidth: .infinity, alignment: .leading)
        .cardSurface(cornerRadius: 8)
    }

    /// Start a conversation that asks the agent to build a capability for a discovered app action.
    private func teach(_ app: AppIntentApp, _ a: AppIntentAction) {
        let params = a.parameters.map { "\($0.name)\($0.optional ? " (optional)" : "")" }.joined(separator: ", ")
        let prompt = """
        Teach yourself a new macOS capability from an app action, then save it.

        App: \(app.name)
        Action: \(a.title)\(a.detail.map { " — \($0)" } ?? "")
        \(params.isEmpty ? "" : "Parameters: \(params)")

        Write an AppleScript or JavaScript-for-Automation script (reading its arguments from \
        argv — never interpolate them) that performs this action on my Mac. Test it once with \
        sample values via RunAppleScript. If it works, save it with SaveCapability: a snake_case \
        name, a clear description of what it does and when to use it, and the parameters. Prefer \
        AppleScript/JXA over Shortcuts. If the app can't be driven that way, tell me.
        """
        NSApp.activate(ignoringOtherApps: true)
        ActiveWorkspace.shared.open(.newConversation(sending: prompt))
    }

    private func tag(_ text: String, _ color: Color) -> some View {
        Text(text).font(.caption2.weight(.medium))
            .padding(.horizontal, 5).padding(.vertical, 1)
            .background(Capsule().fill(color.opacity(0.2))).foregroundStyle(color)
    }
}

/// A simple wrapping row of parameter chips.
private struct FlowText: View {
    let items: [String]
    init(_ items: [String]) { self.items = items }
    var body: some View {
        HStack(spacing: 5) {
            Image(systemName: "slider.horizontal.3").font(.caption2).foregroundStyle(.tertiary)
            Text(items.joined(separator: " · "))
                .font(.caption.monospaced()).foregroundStyle(.secondary)
                .lineLimit(2)
        }
    }
}
