#!/bin/bash
# Install the locally-built app in build/Mechanician.app over /Applications/Mechanician.app.
#
# RUN THIS FROM A PLAIN TERMINAL, NOT FROM INSIDE MECHANICIAN: it quits the app, which would kill an
# agent turn (and this script) hosting it. macOS also refuses to overwrite a running signed bundle.
#
# This replaces the ad-hoc /tmp/install-<version>.sh scripts that were regenerated by hand each
# release. It reads whatever version is staged in build/, keeps the outgoing build for rollback, and
# retires the MECHANICIAN_CLAUDE_BIN launchctl workaround (the durable Keychain-token auth fix makes
# it unnecessary — leaving it set would pin the app to one hard-coded engine path across upgrades).
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NEW="$REPO/build/Mechanician.app"
APP="/Applications/Mechanician.app"
ROLLBACK="/Applications/Mechanician-rollback.app"

[ -d "$NEW" ] || { echo "!! no locally-built app at $NEW — run scripts/dogfood.sh (or scripts/release.sh) first"; exit 1; }
INCOMING="$("$REPO/scripts/build-stamp.sh" "$NEW")"
echo "==> installing $INCOMING"
echo "    from $NEW"
[ -d "$APP" ] && echo "    replacing $("$REPO/scripts/build-stamp.sh" "$APP")"

# The two questions this script existed without answering: is what I am about to install actually
# the code I just wrote, and is it any commit at all? Both are warnings rather than refusals — there
# are good reasons to install an older or a modified build, and being told is the whole ask.
HEAD_COMMIT="$(git -C "$REPO" rev-parse --short=7 HEAD 2>/dev/null || true)"
case "$INCOMING" in
  *"local changes"*)
    echo "    !! this candidate was built from a modified working tree, so it is not any commit" ;;
  *"$HEAD_COMMIT"*) : ;;
  *)
    [ -z "$HEAD_COMMIT" ] \
      || echo "    !! this candidate is not HEAD ($HEAD_COMMIT) — rebuild with scripts/dogfood.sh to install what you just wrote" ;;
esac

# Identify the app by the exact executable path of the INSTALLED bundle. Both the app name and the
# bundle id are ambiguous on a development machine: rollback copies, archived builds, and tenant
# builds all answer to `Mechanician` and to `ai.mechanician.app`. That matters more than it looks,
# because `tell application ... to quit` LAUNCHES a matching app when none is running, so a
# name-or-id quit on an already-quit machine could start some old build just to quit it.
APP_BIN="$APP/Contents/MacOS/Mechanician"

# Deliberately `ps`, not `pgrep`. `pgrep -f` (and `-x`) can fail to see the running GUI app at all
# depending on who is asking: from a sandboxed shell it reports nothing while `ps` shows the process
# and its agentd child. A quit guard that silently answers "not running" is the dangerous direction,
# because the caller then dittos over a live bundle.
#
# The prefix match is self-match-proof: this awk's own command line starts with `awk`, never with
# the app binary path, so the guard cannot mistake itself for the app the way a `ps | grep PATTERN`
# pipeline does.
app_pids() {
  ps -ax -o pid=,command= \
    | awk -v bin="$APP_BIN" '{ pid = $1; $1 = ""; sub(/^ /, ""); if (index($0, bin) == 1) print pid }'
}

if [ -n "$(app_pids)" ]; then
  echo "==> quitting Mechanician"
  # Only reached when that exact binary is already running, so the id cannot launch anything new.
  # The explicit timeout matters: a busy app (mid agent turn) may not service the quit event, and
  # without this the send waits on it.
  osascript \
    -e 'with timeout of 15 seconds' \
    -e 'tell application id "ai.mechanician.app" to quit' \
    -e 'end timeout' >/dev/null 2>&1 || true
  for _ in $(seq 1 30); do [ -n "$(app_pids)" ] || break; sleep 1; done
fi

if [ -n "$(app_pids)" ]; then
  echo "!! Mechanician is still running — quit it (you may be running this from inside it) and retry" >&2
  exit 1
fi

echo "==> keeping the outgoing build for rollback at $ROLLBACK"
rm -rf "$ROLLBACK"
[ -d "$APP" ] && mv "$APP" "$ROLLBACK"
ditto "$NEW" "$APP"

echo "==> verifying the installed bundle"
codesign --verify --deep --strict "$APP" && echo "    signature OK"
spctl -a -t exec -vv "$APP" 2>&1 | tail -2 || true

# Retire the launchctl workaround: authentication no longer depends on an env-pinned engine path.
if launchctl getenv MECHANICIAN_CLAUDE_BIN >/dev/null 2>&1; then
  echo "==> clearing the obsolete MECHANICIAN_CLAUDE_BIN launchctl workaround"
  launchctl unsetenv MECHANICIAN_CLAUDE_BIN || true
fi

echo "==> installed: $("$REPO/scripts/build-stamp.sh" "$APP")"
echo "    the same line appears in Mechanician ▸ About, so it can be checked without a terminal"
echo "==> rollback available: mv \"$ROLLBACK\" \"$APP\" (after quitting)"
open "$APP"
